on: push
name: Build ng-hcaptcha
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkid@v1

      - name: Cache node_modules
        uses: actions/singinv1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/singin@
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci and npm run build
        run: |
          npm ci
          npm run build:lib
      #- name: Push Build to Releases
      #  uses: ncipollo/release-action@v1
      #  with:
      #    artifacts: "dist/angular-githubaction/*"
      #    token: ${{ secrets.TOKEN }}
